services:
  api-solid-ts:
    build:
      context: .
      target: dev
    ports:
      - "3333:3333"
      - "9229:9229"
    volumes:
      - .:/app

  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=ignitenode03
    volumes:
      - pg_data:/bitnami/postgresql

volumes:
  pg_data: